name: asm1_sync
description: "SYNC - Secure Your Neural Cognition. Aplikasi jurnal aman dengan enkripsi AES-256 dan autentikasi biometrik."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0 # Autentikasi sidik jari
  encrypt: ^5.0.3 # Framework Kriptografi AES-256
  path_provider: ^2.1.5 # Mendapatkan direktori penyimpanan perangkat
  flutter_secure_storage: ^9.2.4 # Menyimpan kunci enkripsi dengan aman di Keystore/Keychain
  intl: ^0.20.2 # Format tanggal & waktu dalam Bahasa Indonesia
  google_fonts: ^6.2.1 # Font DM Sans via CDN
  screen_protector: ^1.5.1 # Memblokir screenshot

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_no-bg.png
